### ISSUE TITLE
is it the same thing with klog?

### ISSUE THREAD

**Issue by reverland** [armsword/dlog#1]
https://github.com/kingsamchen/KLog

**Comment by armsword** [comment]
看了下，不一样啊。他的是Windows版本，用的是C++ 11，我的是Linux下的，用的C++ 0X，设计思路也不一样。

简单的看了下成员变量，他巧妙的使用了双Buffer，这个是对性能提高很有帮助的技巧，我没使用的主要原因是log库只是为了验证自己一些想法，虽然之前一直是知道这种优化方法的。
